name: build-docker-image
on:
  push:
    paths:
      - 'image/**'

jobs:
  build-and-push-docker-image:
    name: Build and push docker image to docker hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2.0.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Extract metadata (tags,labels) for Docker
        uses: docker/metadata-action@v4
        id: meta

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./image/
          images: name=${{ secrets.DOCKERHUB_USERNAME }}/mitoanalyzer
          tags: v${{ steps.meta.outputs.labels.version }}
